routes/web.php
<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/', function () {
    return redirect('/blog/posts');
});

Route::group([
    'prefix' => 'blog',
    'as'     => 'blog.',
], function (): void {
    Route::get('/', function () {
        return redirect('/blog/posts');
    });

    Route::get(
        'subscribe',
        'SubscribesController@subscribe'
    )->name('subscribe');

    Route::resource(
        'posts',
        'PostsController'
    )->only(['index', 'show']);
});

Route::group([
    'prefix'     => 'admin',
    'as'         => 'admin.',
    'middleware' => 'auth',
], function (): void {
    Route::get('', 'AdminsController@index');

    Route::get('posts/{post}', 'AdminsController@update')->name('form.update');

    Route::resource(
        'posts',
        'PostsController'
    )->only(['update', 'destroy', 'store']);
});

app/Models/Post.php
<?php

declare(strict_types=1);

namespace App\Models;

use Carbon\Carbon;
use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * App\Models\Post.
 *
 * @property int                   $id
 * @property string                $title
 * @property string|null           $text
 * @property int|null              $user_id
 * @property Carbon|null           $created_at
 * @property Carbon|null           $updated_at
 * @property \App\Models\User|null $user
 *
 * @method static Builder|Post newModelQuery()
 * @method static Builder|Post newQuery()
 * @method static Builder|Post query()
 * @method static Builder|Post whereCreatedAt($value)
 * @method static Builder|Post whereId($value)
 * @method static Builder|Post whereText($value)
 * @method static Builder|Post whereTitle($value)
 * @method static Builder|Post whereUpdatedAt($value)
 * @method static Builder|Post whereUserId($value)
 * @mixin Eloquent
 *
 * @property int|null $chars_count
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Post whereCharsCount($value)
 */
class Post extends Model
{
    protected $table = 'posts';

    public function user(): belongsTo
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/PostsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Http\Requests\Post\StoreRequest;
use App\Http\Requests\Post\UpdateRequest;
use App\Models\Post;
use Exception;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

/**
 * Class PostController.
 */
class PostsController extends Controller
{
    /**
     * @return View
     */
    public function index(): View
    {
        $posts = Post::paginate(5);

        return view('posts.index', ['posts' => $posts]);
    }

    /**
     * @param Post $post
     *
     * @return View
     */
    public function show(Post $post): View
    {
        return view('posts.show', ['post' => $post]);
    }

    /**
     * @param StoreRequest $request
     *
     * @return View
     */
    public function store(StoreRequest $request): View
    {
        $post = $this->createPost($request);

        return view('admins.posts.update', ['post' => $post]);
    }

    /**
     * @param StoreRequest $request
     *
     * @return Post
     */
    private function createPost(StoreRequest $request): Post
    {
        $post = new Post();

        $post->title       = $request->title;
        $post->text        = $request->text;
        $post->chars_count = strlen($request->text);

        $post->save();

        return $post;
    }

    /**
     * @param Post $post
     *
     * @return RedirectResponse
     *
     * @throws Exception
     */
    public function destroy(Post $post): RedirectResponse
    {
        $post->delete();

        return redirect()->route('admins.home');
    }

    /**
     * @param Post          $post
     * @param UpdateRequest $request
     *
     * @return View
     */
    public function update(Post $post, UpdateRequest $request): View
    {
        $post = $this->updatePost($post, $request);

        return view('admins.posts.update', ['post' => $post]);
    }

    /**
     * @param Post          $post
     * @param UpdateRequest $request
     *
     * @return Post
     */
    private function updatePost(Post $post, UpdateRequest $request): Post
    {
        if (isset($request->title)) {
            $post->title = $request->title;
        }

        if (isset($request->text)) {
            $post->text        = $request->text;
            $post->chars_count = strlen($request->text);
        }

        $post->save();

        return $post;
    }
}

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    @foreach($posts as $post)
        <div class="blog-post pl-3">
            <h2 class="blog-post-title"><a href="{{ route('blog.posts.show', $post) }}">{{ $post->title }}</a></h2>
            <p class="blog-post-meta">
                <span class="badge badge-dark">{{ $post->updated_at->format('d.m.Y H:i') }}</span>
                <span class="badge badge-warning">{{ $post->chars_count }} символов</span>
            </p>

            <p>{{ Illuminate\Support\Str::limit($post->text, 1000) }}</p>

            <a href="{{ action('PostsController@show', $post) }}" type="button" class="btn btn-secondary btn-sm text-light">Читать далее</a>
            <hr class="mt-2 mb-3"/>
        </div>
    @endforeach
    {{ $posts->links() }}
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-light">
            <li class="breadcrumb-item"><a href="{{ url('/blog/posts') }}">Блог</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ Illuminate\Support\Str::limit($post->title, 100) }}</li>
        </ol>
    </nav>

        <div class="blog-post pl-3">
            <h2 class="blog-post-title">{{ $post->title }}</h2>
            <p class="blog-post-meta">
                <span class="badge badge-primary">{{ $post->updated_at->format('d.m.Y H:i') }}</span>
                <span class="badge badge-warning">{{ $post->chars_count }} символов</span>
            </p>

            <p>{{ $post->text }}</p>
        </div>
@endsection